### ISSUE TITLE
vegas mode should be disabled by default

### ISSUE THREAD

**Issue by jvermillard** [mangOH/YellowVegasMode#2]
if yellow is targeting battery powered app, the vegas mode should be off by default and enabled by octave or some other configuration if needed

**Comment by jtchitty** [comment]
The vegas mode is on by default for out-of-box experience.  It can be disabled using the `hello` command-line tool or the Config API.  It was never intended to be a permanent app.  It is not required by any sensor or actuator and both the vegasMode and helloYellow apps should be removed when using mangOH for a serious purpose.
